services:
  code:
    entrypoint:
      - sleep
      - infinity
    image: huggingface/transformers-pytorch-gpu
    volumes:
      - .:/com.docker.devenvironments.code
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  tts:
    build:
      context: ./tts/app
      dockerfile: Dockerfile
    working_dir: /app
    command: streamlit run app.py